//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gadz.Tetris.Resources.Textos
{
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Jogo
    {
        /// <summary>
        /// Defines the resourceMan
        /// </summary>
        private static global::System.Resources.ResourceManager resourceMan;

        /// <summary>
        /// Defines the resourceCulture
        /// </summary>
        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Initializes a new instance of the <see cref="Jogo"/> class.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Jogo()
        {
        }

        /// <summary>
        /// Gets the ResourceManager
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gadz.Tetris.Resources.Textos.Jogo", typeof(Jogo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Gets or sets the Culture
        /// Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Gets the Ajuda
        /// Looks up a localized string similar to Ajuda.
        /// </summary>
        public static string Ajuda
        {
            get
            {
                return ResourceManager.GetString("Ajuda", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the EscolheEstilo
        /// Looks up a localized string similar to Escolha o estilo.
        /// </summary>
        public static string EscolheEstilo
        {
            get
            {
                return ResourceManager.GetString("EscolheEstilo", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the Iniciar
        /// Looks up a localized string similar to Iniciar.
        /// </summary>
        public static string Iniciar
        {
            get
            {
                return ResourceManager.GetString("Iniciar", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the Linhas
        /// Looks up a localized string similar to Linhas.
        /// </summary>
        public static string Linhas
        {
            get
            {
                return ResourceManager.GetString("Linhas", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the Nivel
        /// Looks up a localized string similar to Nível.
        /// </summary>
        public static string Nivel
        {
            get
            {
                return ResourceManager.GetString("Nivel", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the Nome
        /// Looks up a localized string similar to Tetris.
        /// </summary>
        public static string Nome
        {
            get
            {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the Pausado
        /// Looks up a localized string similar to Paused.
        /// </summary>
        public static string Pausado
        {
            get
            {
                return ResourceManager.GetString("Pausado", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the Pontuacao
        /// Looks up a localized string similar to Pontos.
        /// </summary>
        public static string Pontuacao
        {
            get
            {
                return ResourceManager.GetString("Pontuacao", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the PressioneEnterParaContinuar
        /// Looks up a localized string similar to Press ENTER to continue.
        /// </summary>
        public static string PressioneEnterParaContinuar
        {
            get
            {
                return ResourceManager.GetString("PressioneEnterParaContinuar", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the PressioneParaContinuar
        /// Looks up a localized string similar to Press any key to continue.
        /// </summary>
        public static string PressioneParaContinuar
        {
            get
            {
                return ResourceManager.GetString("PressioneParaContinuar", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the Proximo
        /// Looks up a localized string similar to Próximo.
        /// </summary>
        public static string Proximo
        {
            get
            {
                return ResourceManager.GetString("Proximo", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the Sobre
        /// Looks up a localized string similar to Sobre.
        /// </summary>
        public static string Sobre
        {
            get
            {
                return ResourceManager.GetString("Sobre", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the SomDesligado
        /// Looks up a localized string similar to Som desligado.
        /// </summary>
        public static string SomDesligado
        {
            get
            {
                return ResourceManager.GetString("SomDesligado", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the SomLigado
        /// Looks up a localized string similar to Som ligado.
        /// </summary>
        public static string SomLigado
        {
            get
            {
                return ResourceManager.GetString("SomLigado", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the Tempo
        /// Looks up a localized string similar to Tempo.
        /// </summary>
        public static string Tempo
        {
            get
            {
                return ResourceManager.GetString("Tempo", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the ToggleSoundKey
        /// Looks up a localized string similar to Aperte SHIFT para ligar ou desligar o som.
        /// </summary>
        public static string ToggleSoundKey
        {
            get
            {
                return ResourceManager.GetString("ToggleSoundKey", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the Velocidade
        /// Looks up a localized string similar to Velocidade.
        /// </summary>
        public static string Velocidade
        {
            get
            {
                return ResourceManager.GetString("Velocidade", resourceCulture);
            }
        }
    }
}
