//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gadz.Tetris.Resources.Textos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Jogo_pt {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Jogo_pt() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gadz.Tetris.Resources.Textos.Jogo-pt", typeof(Jogo_pt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Ajuda {
            get {
                return ResourceManager.GetString("Ajuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the style.
        /// </summary>
        public static string EscolheEstilo {
            get {
                return ResourceManager.GetString("EscolheEstilo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Iniciar {
            get {
                return ResourceManager.GetString("Iniciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        public static string Linhas {
            get {
                return ResourceManager.GetString("Linhas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Nivel {
            get {
                return ResourceManager.GetString("Nivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tetris.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausado.
        /// </summary>
        public static string Pausado {
            get {
                return ResourceManager.GetString("Pausado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Pontuacao {
            get {
                return ResourceManager.GetString("Pontuacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressione ENTER para continuar.
        /// </summary>
        public static string PressioneEnterParaContinuar {
            get {
                return ResourceManager.GetString("PressioneEnterParaContinuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressione qualquer tecla para continuar.
        /// </summary>
        public static string PressioneParaContinuar {
            get {
                return ResourceManager.GetString("PressioneParaContinuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Proximo {
            get {
                return ResourceManager.GetString("Proximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Sobre {
            get {
                return ResourceManager.GetString("Sobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Off.
        /// </summary>
        public static string SomDesligado {
            get {
                return ResourceManager.GetString("SomDesligado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound On.
        /// </summary>
        public static string SomLigado {
            get {
                return ResourceManager.GetString("SomLigado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Tempo {
            get {
                return ResourceManager.GetString("Tempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press SHIFT to turn the sound on or off.
        /// </summary>
        public static string ToggleSoundKey {
            get {
                return ResourceManager.GetString("ToggleSoundKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Velocidade {
            get {
                return ResourceManager.GetString("Velocidade", resourceCulture);
            }
        }
    }
}
